/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author user
 */
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class tes extends javax.swing.JFrame {

    /**
     * Creates new form tes
     */
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public tes() {
        initComponents();
        combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfKelas = new javax.swing.JTextField();
        tfNIM = new javax.swing.JTextField();
        chKalkulus = new javax.swing.JCheckBox();
        chPBO = new javax.swing.JCheckBox();
        chJarkom = new javax.swing.JCheckBox();
        chEnglish = new javax.swing.JCheckBox();
        chSenin = new javax.swing.JCheckBox();
        chSelasa = new javax.swing.JCheckBox();
        chRabu = new javax.swing.JCheckBox();
        chKamis = new javax.swing.JCheckBox();
        chJumat = new javax.swing.JCheckBox();
        chSabtu = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        cbJadwal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txOutput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMatkul = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Nama            :");

        jLabel6.setText("NIM               :");

        jLabel7.setText("KELAS            :");

        jLabel8.setText("Pilihan Matkul :");

        jLabel9.setText("Hari               :");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        tfKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKelasActionPerformed(evt);
            }
        });

        tfNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNIMActionPerformed(evt);
            }
        });

        chKalkulus.setText("Kalkulus");
        chKalkulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chKalkulusActionPerformed(evt);
            }
        });

        chPBO.setText("PBO");
        chPBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chPBOActionPerformed(evt);
            }
        });

        chJarkom.setText("Jarkom");
        chJarkom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chJarkomActionPerformed(evt);
            }
        });

        chEnglish.setText("English");
        chEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEnglishActionPerformed(evt);
            }
        });

        chSenin.setText("Senin");
        chSenin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSeninActionPerformed(evt);
            }
        });

        chSelasa.setText("Selasa");
        chSelasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSelasaActionPerformed(evt);
            }
        });

        chRabu.setText("Rabu");
        chRabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chRabuActionPerformed(evt);
            }
        });

        chKamis.setText("Kamis");
        chKamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chKamisActionPerformed(evt);
            }
        });

        chJumat.setText("Jumat");
        chJumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chJumatActionPerformed(evt);
            }
        });

        chSabtu.setText("Sabtu");
        chSabtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSabtuActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");

        cbJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJadwalActionPerformed(evt);
            }
        });

        jLabel2.setText("Jadwal         :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chKalkulus)
                            .addComponent(chEnglish)
                            .addComponent(chJarkom)
                            .addComponent(chPBO)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(chRabu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chSabtu))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chSelasa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chJumat))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chSenin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chKamis)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbJadwal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chKalkulus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chPBO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chJarkom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chEnglish)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chSenin)
                    .addComponent(chKamis))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chSelasa)
                    .addComponent(chJumat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chRabu)
                    .addComponent(chSabtu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txOutput.setColumns(20);
        txOutput.setRows(5);
        jScrollPane3.setViewportView(txOutput);

        jScrollPane2.setViewportView(listMatkul);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jLabel1.setText("IDENTITAS");

        jLabel3.setText("LIST MATKUL");

        jLabel4.setText("OUTPUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(315, 315, 315)
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKelasActionPerformed

    private void tfNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNIMActionPerformed

    private void chKalkulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chKalkulusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chKalkulusActionPerformed

    private void chPBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chPBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chPBOActionPerformed

    private void chJarkomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chJarkomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chJarkomActionPerformed

    private void chEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chEnglishActionPerformed

    private void chSeninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSeninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chSeninActionPerformed

    private void chSelasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSelasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chSelasaActionPerformed

    private void chRabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chRabuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chRabuActionPerformed

    private void chKamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chKamisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chKamisActionPerformed

    private void chJumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chJumatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chJumatActionPerformed

    private void chSabtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSabtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chSabtuActionPerformed

    private void cbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        
        
    }
    private void combobox(){
        try{
            con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "PBO", "tubes");//link sql
            String sql = "select id_jadwal from jadwal";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                String name = rs.getString("id_jadwal");
                cbJadwal.addItem(name); 
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public String getNama(){
        return tfNama.getText();
    }
    
    public String getTfKelas() {
        return tfKelas.getText();
    }

    public String getTfNIM() {
        return tfNIM.getText();
    }
    
    public JButton getBtnAdd() {
        return btnAdd;
    }

    
    public ArrayList<String> getMatkul(){
        ArrayList<String> s = new ArrayList();
        if (chKalkulus.isSelected()) {
            s.add(chKalkulus.getText());
        }
        if (chPBO.isSelected()) {
            s.add(chPBO.getText());
        }
        if (chJarkom.isSelected()) {
            s.add(chJarkom.getText());
        }
        if (chEnglish.isSelected()) {
            s.add(chEnglish.getText());
        }
        return s;
    }
    
    public int getSelectedPeserta(){
        return listMatkul.getSelectedIndex();
    }
    
    public void setDaftarPeserta(String[] daftarID){
        listMatkul.setListData(daftarID);
    }

    public void setTexPeserta(String s) {
        txOutput.setText(s);
    }
    public void resetView(){
        tfNama.setText("");
        tfNIM.setText("");
        tfKelas.setText("");
        chKalkulus.setSelected(false);
        chPBO.setSelected(false);
        chJarkom.setSelected(false);
        chEnglish.setSelected(false);
        listMatkul.clearSelection();
    }
    
    public JList getListMatkul() {
        return listMatkul;
    }
    
    public void addActionListener(ActionListener e){
        btnAdd.addActionListener(e);

    }
    
    public void addMouseAdapter(MouseAdapter e){
        listMatkul.addMouseListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JCheckBox chEnglish;
    private javax.swing.JCheckBox chJarkom;
    private javax.swing.JCheckBox chJumat;
    private javax.swing.JCheckBox chKalkulus;
    private javax.swing.JCheckBox chKamis;
    private javax.swing.JCheckBox chPBO;
    private javax.swing.JCheckBox chRabu;
    private javax.swing.JCheckBox chSabtu;
    private javax.swing.JCheckBox chSelasa;
    private javax.swing.JCheckBox chSenin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listMatkul;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNIM;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextArea txOutput;
    // End of variables declaration//GEN-END:variables
}
